### ISSUE TITLE
CreateWithAttributes method will fail

### ISSUE THREAD

**Issue by chmoelders** [spatie/larabank-projectors#21]
Hi Spatie-Team!

Thank you for the great packages and examples related to event-sourcing! 

I assume the lines below does only work if the queue driver is set to *sync* or if you have a very fast or empty queue, otherwise the account isn't persisted and uuid() will return null. Isn't it?

https://github.com/spatie/larabank-projectors/blob/master/app/Account.php#L18-L34

Can you please show me your preferred way to create an instance.

**Comment by freekmurze** [comment]
`$uuid` will always contain a value, even if you have slow queues.

To know more about event sourcing, consider picking up our upcoming course: https://event-sourcing-laravel.com

**Comment by chmoelders** [comment]
How can that be?

If `AccountsProjector::onAccountCreated(AccountCreated $event)` hasn't handled the event, there we will not be an Account with the given `UUID` in the database table.

Thank you for the Link to the course. I'm already registered for the newsletter a while.

**Comment by freekmurze** [comment]
> How can that be?

Ah, you're right, this example assumes that this is being performed in sync
